### ISSUE TITLE
If I have a lot of datasets, I cannot see them all

### ISSUE THREAD

**Issue by srosset81** [mguihal/tripleAdmin#13]
See attached screenshot. There is no scrollbar to see all datasets.

![Capture d’écran du 2024-12-25 18-22-14](https://github.com/user-attachments/assets/c21ffb55-dbb3-4b08-88f7-be70468596b8)

**Comment by mguihal** [comment]
Fixed in release [v0.2.0](https://github.com/mguihal/tripleAdmin/releases/tag/v0.2.0)
