### ISSUE TITLE
Pass host and username as environment variables

### ISSUE THREAD

**Issue by srosset81** [mguihal/tripleAdmin#7]
When deploying tripleadmin to a server, the host and the username will be the same.

So to make it easier to access the tripleadmin interface, it would be useful if they could be set as env variables.

**Comment by mguihal** [comment]
Fixed in release [v0.2.0](https://github.com/mguihal/tripleAdmin/releases/tag/v0.2.0)

**Comment by srosset81** [comment]
Works great, thank you !
